name: Verify macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         edition: ["enterprise", "community"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build and Verify"
        env:
          EDITION: ${{ matrix.edition }}
        run: |
          VERSION=$(cat version.txt)
          ./scripts/verify_linux.sh ${VERSION} ${EDITION}
          