name: Verify windows zip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  verify:
    runs-on: windows-latest
    strategy:
       matrix:
         edition: ["enterprise", "community"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build and Verify"
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          VERSION=$(cat version.txt)
          ./desktop/scripts/verify_windows.sh ${VERSION} ${{ matrix.edition }}
