name: Verify linux amd64 deb

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
       matrix:
        platform: ["ubuntu-20.04", "debian-10"]
        edition: ["enterprise", "community"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: "Build and Verify"
        run: |
          cd desktop
          VERSION=$(cat ../version.txt)
          docker compose run -e ARCH=amd64 -e VERSION=${VERSION} -e EDITION=${{ matrix.edition }} ${{ matrix.platform }}
