version: "3.9"
services:
  ubuntu-20.04:
    build:
      context: .
      args:
        - PLATFORM=ubuntu
        - PLATFORM_VERSION=20.04
        - ARCH=${ARCH:-arm64}
        - VERSION=${VERSION:-3.1.0}
        - EDITION=${EDITION:-enterprise}
  ubuntu-22.04:
    build:
      context: .
      args:
        - PLATFORM=ubuntu
        - PLATFORM_VERSION=22.04
        - ARCH=${ARCH:-arm64}
        - VERSION=${VERSION:-3.1.0}
        - EDITION=${EDITION:-enterprise}
  debian-9:
    build:
      context: .
      args:
        - PLATFORM=debian
        - PLATFORM_VERSION=9
        - ARCH=${ARCH:-amd64}
        - VERSION=${VERSION:-3.1.0}
        - EDITION=${EDITION:-enterprise}
    profiles:
      - debian-9
  debian-10:
    build:
      context: .
      args:
        - PLATFORM=debian
        - PLATFORM_VERSION=10
        - ARCH=${ARCH:-arm64}
        - VERSION=${VERSION:-3.1.0}
        - EDITION=${EDITION:-enterprise}
  debian-11:
    build:
      context: .
      args:
        - PLATFORM=debian
        - PLATFORM_VERSION=11
        - ARCH=${ARCH:-arm64}
        - VERSION=${VERSION:-3.1.0}
        - EDITION=${EDITION:-enterprise}