version: "3.9"
services:
  cbl-c-verify:
    environment:
      - CBL_VERSION=${CBL_VERSION:-3.2.1}
      - CBL_BUILD=${CBL_BUILD:-0}
      - CBL_EDITION=${CBL_EDITION:-enterprise}
      - CBL_ARCH=${CBL_ARCH:-arm64}
    build:
      context: .
      args:
        - OS_NAME=${OS_NAME:-debian}
        - OS_VERSION=${OS_VERSION:-11}
        - OS_ARCH=${CBL_ARCH:-arm64}
        